# Generated by Django 4.0.1 on 2022-01-13 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pet'),
        ),
        migrations.AddField(
            model_name='booking',
            name='sitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.sitter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_bookings',
            field=models.ManyToManyField(through='api.Booking', to='api.Sitter'),
        ),
        migrations.AddField(
            model_name='pet',
            name='primary_care_sitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_pets', to='api.sitter'),
            preserve_default=False,
        ),
    ]
