# Generated by Django 4.0.1 on 2022-01-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default='12345', max_length=5),
        ),
    ]
