# Generated by Django 4.0.1 on 2022-01-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
