# Generated by Django 4.0.1 on 2022-01-13 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booking_pet_booking_sitter_pet_pet_bookings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sitter'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='primary_care_sitter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_pets', to='api.sitter'),
        ),
    ]
