# Generated by Django 4.0.1 on 2022-01-13 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pet_primary_care_sitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pet_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sitter'),
        ),
        migrations.AddField(
            model_name='sitter',
            name='sitter_reviews',
            field=models.ManyToManyField(through='api.Review', to=settings.AUTH_USER_MODEL),
        ),
    ]
