# Generated by Django 4.0.1 on 2022-01-27 22:20

import api.models.pet
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.pet.upload_path),
        ),
    ]
