# Generated by Django 4.0.1 on 2022-01-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_review_updated_at_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sitter',
            field=models.BooleanField(default=False),
        ),
    ]
