# Generated by Django 4.0.1 on 2022-01-13 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sitter_sitter_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_bookings',
        ),
        migrations.RemoveField(
            model_name='sitter',
            name='sitter_reviews',
        ),
        migrations.AddField(
            model_name='booking',
            name='pet_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitter',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mysitter', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitter',
            name='sitter_booking',
            field=models.ManyToManyField(through='api.Booking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.sitter'),
            preserve_default=False,
        ),
    ]
