# Generated by Django 4.0.1 on 2022-01-10 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_sitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='pet',
            new_name='owner_pet',
        ),
        migrations.AddField(
            model_name='pet',
            name='booking_pet',
            field=models.ManyToManyField(through='api.Booking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_pet', to=settings.AUTH_USER_MODEL),
        ),
    ]
