# Generated by Django 4.0.1 on 2022-01-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_pet_booking_owner_pet_booking_pet_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pet_owner',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_sitter',
        ),
    ]
