# Generated by Django 4.0.1 on 2022-01-13 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_booking_pet_remove_pet_pet_bookings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter',
            name='email',
        ),
        migrations.AlterField(
            model_name='sitter',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mysitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='sitter_booking',
            field=models.ManyToManyField(through='api.Booking', to=settings.AUTH_USER_MODEL),
        ),
    ]
