# Generated by Django 4.0.1 on 2022-01-13 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_booking_end_date_alter_booking_sitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='sitter_booking',
            field=models.ManyToManyField(through='api.Booking', to=settings.AUTH_USER_MODEL),
        ),
    ]
