# Generated by Django 4.0.1 on 2022-01-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_sitter_sitter_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sitter',
            name='sitter_booking',
        ),
    ]
