# Generated by Django 4.0.1 on 2022-01-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_booking_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pet',
        ),
    ]
