# Generated by Django 4.0.1 on 2022-01-10 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_booking_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='owner_of_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_owmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitter_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
