# Generated by Django 4.0.1 on 2022-01-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_pet_booking_owner_pet_pet_booking_pet_and_more'),
        ('api', '0013_alter_booking_owner_of_pet_alter_booking_sitter'),
    ]

    operations = [
    ]
