# Generated by Django 4.0.1 on 2022-01-10 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_booking_owner_of_pet_alter_pet_pet_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_pet', to=settings.AUTH_USER_MODEL),
        ),
    ]
