# Generated by Django 4.0.1 on 2022-01-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_location_user_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default='12345', max_length=5),
        ),
    ]
