# Generated by Django 4.0.1 on 2022-01-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20220113_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
